### ISSUE TITLE
Does the Signer only allow ECPrivateKey?

### ISSUE THREAD

**Issue by alam156** [tsenger/vdstools#9]
Hi, I am trying to create VDS using RSAPrivateKey. But the signer class only allows ECPrivateKey. is there any way to fit RSAPrivateKey while creating VDS?
N.B: My CA certificate is built using RSAPrivateKey.

**Comment by tsenger** [comment]
Hi alam156,
according to the specification, only ECDSA is permitted as a signature for VDS. Therefore, the Signer class does not offer the option of using RSA certificates. An RSA signature would also make the VDS very large.
